[12-Mar-2025 16:52:25 UTC] Error: Undefined variable $flashMessage in C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code on line 10
[12-Mar-2025 16:52:59 UTC] Error: Undefined variable $flashMessage in C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code on line 10
[12-Mar-2025 16:53:03 UTC] Error: Undefined variable $flashMessage in C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code on line 10
[12-Mar-2025 16:56:12 UTC] Error: Undefined variable $flashMessage in C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code on line 10
[12-Mar-2025 16:56:29 UTC] Error: Undefined variable $flashMessage in C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code on line 10
[12-Mar-2025 17:33:42 UTC] Fatal error: Undefined variable $flashMessage in C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code on line 10
[12-Mar-2025 18:23:54 UTC] [2025-03-12 18:23:54] ErrorException: Undefined variable $flashMessage in C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code on line 10
Stack trace:
#0 C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code(10): Ace\ace\Exception\Handler\ExceptionHandler->handleError(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ace\ace\View\View.php(315): eval()
#2 C:\xampp\htdocs\ace\ace\View\View.php(257): Ace\ace\View\View->renderTemplate('test/home', Array)
#3 C:\xampp\htdocs\ace\app\controllers\SiteController.php(31): Ace\ace\View\View->render('test/home', Array)
#4 C:\xampp\htdocs\ace\ace\Ace.php(168): Ace\app\controllers\SiteController->index(Object(Ace\ace\Http\Request), Object(Ace\ace\Http\Response))
#5 C:\xampp\htdocs\ace\ace\Ace.php(116): Ace\ace\Ace->dispatch()
#6 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#7 {main}
[12-Mar-2025 18:23:54 UTC] PHP Warning:  include(C:\xampp\htdocs\ace\ace\Exception\Handler/views/templates/error-template.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\ace\ace\Exception\Handler\ExceptionHandler.php on line 126
[12-Mar-2025 18:23:54 UTC] PHP Warning:  include(): Failed opening 'C:\xampp\htdocs\ace\ace\Exception\Handler/views/templates/error-template.php' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\ace\ace\Exception\Handler\ExceptionHandler.php on line 126
[12-Mar-2025 18:27:35 UTC] [2025-03-12 18:27:35] ErrorException: Undefined variable $flashMessage in C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code on line 10
Stack trace:
#0 C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code(10): Ace\ace\Exception\Handler\ExceptionHandler->handleError(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ace\ace\View\View.php(315): eval()
#2 C:\xampp\htdocs\ace\ace\View\View.php(257): Ace\ace\View\View->renderTemplate('test/home', Array)
#3 C:\xampp\htdocs\ace\app\controllers\SiteController.php(31): Ace\ace\View\View->render('test/home', Array)
#4 C:\xampp\htdocs\ace\ace\Ace.php(168): Ace\app\controllers\SiteController->index(Object(Ace\ace\Http\Request), Object(Ace\ace\Http\Response))
#5 C:\xampp\htdocs\ace\ace\Ace.php(116): Ace\ace\Ace->dispatch()
#6 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#7 {main}
[12-Mar-2025 18:27:35 UTC] PHP Warning:  include(C:\xampp\htdocs\ace\ace\Exception\Handler/errors/error-template.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\ace\ace\Exception\Handler\ExceptionHandler.php on line 126
[12-Mar-2025 18:27:35 UTC] PHP Warning:  include(): Failed opening 'C:\xampp\htdocs\ace\ace\Exception\Handler/errors/error-template.php' for inclusion (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\ace\ace\Exception\Handler\ExceptionHandler.php on line 126
[12-Mar-2025 18:28:14 UTC] [2025-03-12 18:28:14] ErrorException: Undefined variable $flashMessage in C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code on line 10
Stack trace:
#0 C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code(10): Ace\ace\Exception\Handler\ExceptionHandler->handleError(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ace\ace\View\View.php(315): eval()
#2 C:\xampp\htdocs\ace\ace\View\View.php(257): Ace\ace\View\View->renderTemplate('test/home', Array)
#3 C:\xampp\htdocs\ace\app\controllers\SiteController.php(31): Ace\ace\View\View->render('test/home', Array)
#4 C:\xampp\htdocs\ace\ace\Ace.php(168): Ace\app\controllers\SiteController->index(Object(Ace\ace\Http\Request), Object(Ace\ace\Http\Response))
#5 C:\xampp\htdocs\ace\ace\Ace.php(116): Ace\ace\Ace->dispatch()
#6 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#7 {main}
[12-Mar-2025 18:30:27 UTC] [2025-03-12 18:30:27] ErrorException: Undefined variable $flashMessage in C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code on line 10
Stack trace:
#0 C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code(10): Ace\ace\Exception\Handler\ExceptionHandler->handleError(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ace\ace\View\View.php(315): eval()
#2 C:\xampp\htdocs\ace\ace\View\View.php(257): Ace\ace\View\View->renderTemplate('test/home', Array)
#3 C:\xampp\htdocs\ace\app\controllers\SiteController.php(31): Ace\ace\View\View->render('test/home', Array)
#4 C:\xampp\htdocs\ace\ace\Ace.php(168): Ace\app\controllers\SiteController->index(Object(Ace\ace\Http\Request), Object(Ace\ace\Http\Response))
#5 C:\xampp\htdocs\ace\ace\Ace.php(116): Ace\ace\Ace->dispatch()
#6 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#7 {main}
[12-Mar-2025 18:39:59 UTC] [2025-03-12 18:39:59] ErrorException: Undefined variable $flashMessage in C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code on line 10
Stack trace:
#0 C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code(10): Ace\ace\Exception\Handler\ExceptionHandler->handleError(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ace\ace\View\View.php(315): eval()
#2 C:\xampp\htdocs\ace\ace\View\View.php(257): Ace\ace\View\View->renderTemplate('test/home', Array)
#3 C:\xampp\htdocs\ace\app\controllers\SiteController.php(31): Ace\ace\View\View->render('test/home', Array)
#4 C:\xampp\htdocs\ace\ace\Ace.php(168): Ace\app\controllers\SiteController->index(Object(Ace\ace\Http\Request), Object(Ace\ace\Http\Response))
#5 C:\xampp\htdocs\ace\ace\Ace.php(116): Ace\ace\Ace->dispatch()
#6 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#7 {main}
[12-Mar-2025 18:44:31 UTC] [2025-03-12 18:44:31] ErrorException: Undefined variable $flashMessage in C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code on line 10
Stack trace:
#0 C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code(10): Ace\ace\Exception\Handler\ExceptionHandler->handleError(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ace\ace\View\View.php(315): eval()
#2 C:\xampp\htdocs\ace\ace\View\View.php(257): Ace\ace\View\View->renderTemplate('test/home', Array)
#3 C:\xampp\htdocs\ace\app\controllers\SiteController.php(31): Ace\ace\View\View->render('test/home', Array)
#4 C:\xampp\htdocs\ace\ace\Ace.php(168): Ace\app\controllers\SiteController->index(Object(Ace\ace\Http\Request), Object(Ace\ace\Http\Response))
#5 C:\xampp\htdocs\ace\ace\Ace.php(116): Ace\ace\Ace->dispatch()
#6 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#7 {main}
[12-Mar-2025 18:52:48 UTC] [2025-03-12 18:52:48] ErrorException: Undefined variable $flashMessage in C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code on line 10
Stack trace:
#0 C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code(10): Ace\ace\Exception\Handler\ExceptionHandler->handleError(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ace\ace\View\View.php(315): eval()
#2 C:\xampp\htdocs\ace\ace\View\View.php(257): Ace\ace\View\View->renderTemplate('test/home', Array)
#3 C:\xampp\htdocs\ace\app\controllers\SiteController.php(31): Ace\ace\View\View->render('test/home', Array)
#4 C:\xampp\htdocs\ace\ace\Ace.php(168): Ace\app\controllers\SiteController->index(Object(Ace\ace\Http\Request), Object(Ace\ace\Http\Response))
#5 C:\xampp\htdocs\ace\ace\Ace.php(116): Ace\ace\Ace->dispatch()
#6 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#7 {main}
[12-Mar-2025 19:10:48 UTC] [2025-03-12 19:10:48] ErrorException: Undefined variable $flashMessage in C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code on line 10
Stack trace:
#0 C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code(10): Ace\ace\Exception\Handler\ExceptionHandler->handleError(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ace\ace\View\View.php(315): eval()
#2 C:\xampp\htdocs\ace\ace\View\View.php(257): Ace\ace\View\View->renderTemplate('test/home', Array)
#3 C:\xampp\htdocs\ace\app\controllers\SiteController.php(31): Ace\ace\View\View->render('test/home', Array)
#4 C:\xampp\htdocs\ace\ace\Ace.php(168): Ace\app\controllers\SiteController->index(Object(Ace\ace\Http\Request), Object(Ace\ace\Http\Response))
#5 C:\xampp\htdocs\ace\ace\Ace.php(116): Ace\ace\Ace->dispatch()
#6 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#7 {main}
[12-Mar-2025 19:16:04 UTC] [2025-03-12 19:16:04] ErrorException: Undefined variable $flashMessage in C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code on line 10
Stack trace:
#0 C:\xampp\htdocs\ace\ace\View\View.php(315) : eval()'d code(10): Ace\ace\Exception\Handler\ExceptionHandler->handleError(2, 'Undefined varia...', 'C:\\xampp\\htdocs...', 10)
#1 C:\xampp\htdocs\ace\ace\View\View.php(315): eval()
#2 C:\xampp\htdocs\ace\ace\View\View.php(257): Ace\ace\View\View->renderTemplate('test/home', Array)
#3 C:\xampp\htdocs\ace\app\controllers\SiteController.php(31): Ace\ace\View\View->render('test/home', Array)
#4 C:\xampp\htdocs\ace\ace\Ace.php(168): Ace\app\controllers\SiteController->index(Object(Ace\ace\Http\Request), Object(Ace\ace\Http\Response))
#5 C:\xampp\htdocs\ace\ace\Ace.php(116): Ace\ace\Ace->dispatch()
#6 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#7 {main}
[12-Mar-2025 21:25:44 UTC] [2025-03-12 21:25:44] Ace\ace\Exception\ContainerNotFoundException: No entry was found for 'Ace\ace\Database\Database'. in C:\xampp\htdocs\ace\ace\Container\Container.php on line 163
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(39): Ace\ace\Container\Container->get('Ace\\ace\\Databas...')
#1 C:\xampp\htdocs\ace\ace\Ace.php(45): Ace\ace\Ace->__construct()
#2 C:\xampp\htdocs\ace\bootstrap\app.php(34): Ace\ace\Ace::getInstance()
#3 C:\xampp\htdocs\ace\public\index.php(13): require('C:\\xampp\\htdocs...')
#4 {main}
[12-Mar-2025 21:25:44 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Ace\ace\Exception\ContainerNotFoundException::getErrorCode() in C:\xampp\htdocs\ace\ace\Exception\Handler\ExceptionHandler.php:164
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Exception\Handler\ExceptionHandler.php(124): Ace\ace\Exception\Handler\ExceptionHandler->getErrorCode(Object(Ace\ace\Exception\ContainerNotFoundException))
#1 C:\xampp\htdocs\ace\ace\Exception\Handler\ExceptionHandler.php(86): Ace\ace\Exception\Handler\ExceptionHandler->renderDevelopmentError(Object(Ace\ace\Exception\ContainerNotFoundException))
#2 [internal function]: Ace\ace\Exception\Handler\ExceptionHandler->handleException(Object(Ace\ace\Exception\ContainerNotFoundException))
#3 {main}
  thrown in C:\xampp\htdocs\ace\ace\Exception\Handler\ExceptionHandler.php on line 164
[12-Mar-2025 21:25:44 UTC] [2025-03-12 21:25:44] ErrorException: Uncaught Error: Call to undefined method Ace\ace\Exception\ContainerNotFoundException::getErrorCode() in C:\xampp\htdocs\ace\ace\Exception\Handler\ExceptionHandler.php:164
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Exception\Handler\ExceptionHandler.php(124): Ace\ace\Exception\Handler\ExceptionHandler->getErrorCode(Object(Ace\ace\Exception\ContainerNotFoundException))
#1 C:\xampp\htdocs\ace\ace\Exception\Handler\ExceptionHandler.php(86): Ace\ace\Exception\Handler\ExceptionHandler->renderDevelopmentError(Object(Ace\ace\Exception\ContainerNotFoundException))
#2 [internal function]: Ace\ace\Exception\Handler\ExceptionHandler->handleException(Object(Ace\ace\Exception\ContainerNotFoundException))
#3 {main}
  thrown in C:\xampp\htdocs\ace\ace\Exception\Handler\ExceptionHandler.php on line 164
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Exception\Handler\ExceptionHandler.php(101): Ace\ace\Exception\Handler\ExceptionHandler->handleError(1, 'Uncaught Error:...', 'C:\\xampp\\htdocs...', 164)
#1 [internal function]: Ace\ace\Exception\Handler\ExceptionHandler->handleShutdown()
#2 {main}
[12-Mar-2025 21:36:12 UTC] [2025-03-12 21:36:12] Ace\ace\Exception\ContainerNotFoundException: No entry was found for 'Ace\ace\Database\Database'. in C:\xampp\htdocs\ace\ace\Container\Container.php on line 163
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(39): Ace\ace\Container\Container->get('Ace\\ace\\Databas...')
#1 C:\xampp\htdocs\ace\ace\Ace.php(45): Ace\ace\Ace->__construct()
#2 C:\xampp\htdocs\ace\bootstrap\app.php(34): Ace\ace\Ace::getInstance()
#3 C:\xampp\htdocs\ace\public\index.php(13): require('C:\\xampp\\htdocs...')
#4 {main}
[12-Mar-2025 21:39:19 UTC] [2025-03-12 21:39:19] Ace\ace\Exception\ContainerNotFoundException: No entry was found for 'Ace\ace\Database\Database'. in C:\xampp\htdocs\ace\ace\Container\Container.php on line 163
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(39): Ace\ace\Container\Container->get('Ace\\ace\\Databas...')
#1 C:\xampp\htdocs\ace\ace\Ace.php(45): Ace\ace\Ace->__construct()
#2 C:\xampp\htdocs\ace\bootstrap\app.php(34): Ace\ace\Ace::getInstance()
#3 C:\xampp\htdocs\ace\public\index.php(13): require('C:\\xampp\\htdocs...')
#4 {main}
[12-Mar-2025 21:43:46 UTC] [2025-03-12 21:43:46] Ace\ace\Exception\ContainerNotFoundException: No entry was found for 'Ace\ace\Database\Database'. in C:\xampp\htdocs\ace\ace\Container\Container.php on line 163
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(39): Ace\ace\Container\Container->get('Ace\\ace\\Databas...')
#1 C:\xampp\htdocs\ace\ace\Ace.php(45): Ace\ace\Ace->__construct()
#2 C:\xampp\htdocs\ace\bootstrap\app.php(34): Ace\ace\Ace::getInstance()
#3 C:\xampp\htdocs\ace\public\index.php(13): require('C:\\xampp\\htdocs...')
#4 {main}
[12-Mar-2025 21:46:39 UTC] [2025-03-12 21:46:39] Ace\ace\Exception\ContainerNotFoundException: No entry was found for 'Ace\ace\Database\Database'. in C:\xampp\htdocs\ace\ace\Container\Container.php on line 163
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(39): Ace\ace\Container\Container->get('Ace\\ace\\Databas...')
#1 C:\xampp\htdocs\ace\ace\Ace.php(45): Ace\ace\Ace->__construct()
#2 C:\xampp\htdocs\ace\bootstrap\app.php(34): Ace\ace\Ace::getInstance()
#3 C:\xampp\htdocs\ace\public\index.php(13): require('C:\\xampp\\htdocs...')
#4 {main}
[12-Mar-2025 21:56:28 UTC] [2025-03-12 21:56:28] Ace\ace\Exception\ContainerNotFoundException: No entry was found for 'Ace\ace\Database\Database'. in C:\xampp\htdocs\ace\ace\Container\Container.php on line 163
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(39): Ace\ace\Container\Container->get('Ace\\ace\\Databas...')
#1 C:\xampp\htdocs\ace\ace\Ace.php(45): Ace\ace\Ace->__construct()
#2 C:\xampp\htdocs\ace\bootstrap\app.php(34): Ace\ace\Ace::getInstance()
#3 C:\xampp\htdocs\ace\public\index.php(13): require('C:\\xampp\\htdocs...')
#4 {main}
[12-Mar-2025 21:57:43 UTC] [2025-03-12 21:57:43] Ace\ace\Exception\ContainerNotFoundException: No entry was found for 'Ace\ace\Database\Database'. in C:\xampp\htdocs\ace\ace\Container\Container.php on line 163
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(39): Ace\ace\Container\Container->get('Ace\\ace\\Databas...')
#1 C:\xampp\htdocs\ace\ace\Ace.php(45): Ace\ace\Ace->__construct()
#2 C:\xampp\htdocs\ace\bootstrap\app.php(34): Ace\ace\Ace::getInstance()
#3 C:\xampp\htdocs\ace\public\index.php(13): require('C:\\xampp\\htdocs...')
#4 {main}
[12-Mar-2025 22:10:29 UTC] [2025-03-12 22:10:29] Ace\ace\Exception\ContainerNotFoundException: No entry was found for 'Ace\ace\Database\Database'. in C:\xampp\htdocs\ace\ace\Container\Container.php on line 163
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(39): Ace\ace\Container\Container->get('Ace\\ace\\Databas...')
#1 C:\xampp\htdocs\ace\ace\Ace.php(45): Ace\ace\Ace->__construct()
#2 C:\xampp\htdocs\ace\bootstrap\app.php(34): Ace\ace\Ace::getInstance()
#3 C:\xampp\htdocs\ace\public\index.php(13): require('C:\\xampp\\htdocs...')
#4 {main}
[12-Mar-2025 22:14:51 UTC] [2025-03-12 22:14:51] Ace\ace\Exception\ContainerNotFoundException: No entry was found for 'Ace\ace\Database\Database'. in C:\xampp\htdocs\ace\ace\Container\Container.php on line 163
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(42): Ace\ace\Container\Container->get('Ace\\ace\\Databas...')
#1 C:\xampp\htdocs\ace\ace\Ace.php(48): Ace\ace\Ace->__construct()
#2 C:\xampp\htdocs\ace\bootstrap\app.php(34): Ace\ace\Ace::getInstance()
#3 C:\xampp\htdocs\ace\public\index.php(13): require('C:\\xampp\\htdocs...')
#4 {main}
[12-Mar-2025 22:15:40 UTC] [2025-03-12 22:15:40] Ace\ace\Exception\ContainerNotFoundException: No entry was found for 'Ace\ace\Database\Database'. in C:\xampp\htdocs\ace\ace\Container\Container.php on line 163
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(42): Ace\ace\Container\Container->get('Ace\\ace\\Databas...')
#1 C:\xampp\htdocs\ace\ace\Ace.php(48): Ace\ace\Ace->__construct()
#2 C:\xampp\htdocs\ace\bootstrap\app.php(34): Ace\ace\Ace::getInstance()
#3 C:\xampp\htdocs\ace\public\index.php(13): require('C:\\xampp\\htdocs...')
#4 {main}
[12-Mar-2025 22:19:14 UTC] [2025-03-12 22:19:14] Ace\ace\Exception\ContainerNotFoundException: No entry was found for 'Ace\ace\Database\Database'. in C:\xampp\htdocs\ace\ace\Container\Container.php on line 163
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(42): Ace\ace\Container\Container->get('Ace\\ace\\Databas...')
#1 C:\xampp\htdocs\ace\ace\Ace.php(48): Ace\ace\Ace->__construct()
#2 C:\xampp\htdocs\ace\bootstrap\app.php(34): Ace\ace\Ace::getInstance()
#3 C:\xampp\htdocs\ace\public\index.php(13): require('C:\\xampp\\htdocs...')
#4 {main}
[12-Mar-2025 22:21:26 UTC] [2025-03-12 22:21:26] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 182
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(130): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:23:15 UTC] [2025-03-12 22:23:15] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 182
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(130): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:27:30 UTC] [2025-03-12 22:27:30] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 174
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(122): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:27:41 UTC] [2025-03-12 22:27:41] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 174
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(122): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:28:42 UTC] [2025-03-12 22:28:42] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 174
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(122): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:28:53 UTC] [2025-03-12 22:28:53] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 174
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(122): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:29:06 UTC] [2025-03-12 22:29:06] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 174
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(122): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:29:18 UTC] [2025-03-12 22:29:18] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 174
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(122): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:30:40 UTC] [2025-03-12 22:30:40] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 195
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(143): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:38:17 UTC] [2025-03-12 22:38:17] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 195
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(143): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:40:12 UTC] [2025-03-12 22:40:12] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 195
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(143): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:42:23 UTC] [2025-03-12 22:42:23] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 195
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(143): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:42:23 UTC] [2025-03-12 22:42:23] ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\ace\ace\Exception\Handler\ExceptionHandler.php:252) in C:\xampp\htdocs\ace\public\index.php on line 19
Stack trace:
#0 [internal function]: Ace\ace\Exception\Handler\ExceptionHandler->handleError(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 19)
#1 C:\xampp\htdocs\ace\public\index.php(19): header('Content-Type: a...')
#2 {main}
[12-Mar-2025 22:42:46 UTC] [2025-03-12 22:42:46] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 195
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(143): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:42:46 UTC] [2025-03-12 22:42:46] ErrorException: Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\ace\ace\Exception\Handler\ExceptionHandler.php:252) in C:\xampp\htdocs\ace\public\index.php on line 19
Stack trace:
#0 [internal function]: Ace\ace\Exception\Handler\ExceptionHandler->handleError(2, 'Cannot modify h...', 'C:\\xampp\\htdocs...', 19)
#1 C:\xampp\htdocs\ace\public\index.php(19): header('Content-Type: a...')
#2 {main}
[12-Mar-2025 22:45:05 UTC] [2025-03-12 22:45:05] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 195
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(143): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:45:38 UTC] [2025-03-12 22:45:38] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 195
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(143): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:45:56 UTC] [2025-03-12 22:45:56] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 195
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(143): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:47:25 UTC] [2025-03-12 22:47:25] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 195
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(143): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:48:15 UTC] [2025-03-12 22:48:15] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 195
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(143): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:49:34 UTC] [2025-03-12 22:49:34] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 195
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(143): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:50:26 UTC] [2025-03-12 22:50:26] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 195
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(143): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:50:34 UTC] [2025-03-12 22:50:34] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 195
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(143): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
[12-Mar-2025 22:51:01 UTC] [2025-03-12 22:51:01] Ace\ace\Exception\HttpException: Controller SitesController not found in C:\xampp\htdocs\ace\ace\Ace.php on line 195
Stack trace:
#0 C:\xampp\htdocs\ace\ace\Ace.php(143): Ace\ace\Ace->dispatch()
#1 C:\xampp\htdocs\ace\public\index.php(16): Ace\ace\Ace->run()
#2 {main}
